### ISSUE TITLE
Dataset.

### ISSUE THREAD

**Issue by danielwilczak101** [desimone/RhinoplastyNet#1]
Hey,

Would you happen to know where I could download the before and after dataset images used for rhino-net. The use would be for a senior design project at my university.

Thank you,
Daniel WIlczak

**Comment by mxa256** [comment]
Hey Daniel, 
Bobby was able to download a zip file of publicly available images from [realself.com](https://www.realself.com/photos?bodyParts=21). This is a website where plastic surgeons/patients can post before and after photos.
Does that help?

Mona

**Comment by danielwilczak101** [comment]
Hey Mona,

This does help a lot! I was able to go on the site and find the images but was not able to find a zip file of all the images. If you know where to grab a zip of it that would be helpful. But if not I can always web scrape all the images off the website.

Thank you,
Daniel

**Comment by mxa256** [comment]
Hey Daniel, 
I see what you are asking. I'll have to ask @desimone , as he was the one who got the zip file. Not sure if he scraped it together -- I'll keep you posted.

Mona

**Comment by desimone** [comment]
@danielwilczak101  I still have the dataset, what's your email?

**Comment by danielwilczak101** [comment]
danielwilczak101@gmail.com

Thank you,
Daniel Wilczak
